describe('template spec', () => {
  it('passes', () => {
    cy.visit('/login')
    cy.get('[data-cy="email-input"]').type('admin@admin.com')
    cy.get('[data-cy="password-input"]').type('123123')
    cy.get('[data-cy="login-button"]').click()
    cy.get('[data-ct="anteproyectos-card"]').click()
    cy.get('[data-cy="create-btn"]').click()
    cy.get('[data-cy="radicado-input"]').type('123456')
    cy.get('[data-cy="titulo-input"]').type('Anteproyecto de prueba 1')
    cy.get('[data-cy="add-Autores-btn"]').click()
    cy.get('[data-cy="search-user-input"]').type('Wall E')
    cy.get('[data-cy="Wall-result"]').click()
    cy.get('[data-cy="add-user-btn"]').click()
    cy.get('[data-cy="add-Directores-btn"]').click()
    cy.get('[data-cy="search-user-input"]').type('Olivia Thomas')
    cy.get('[data-cy="Olivia-result"]').click()
    cy.get('[data-cy="add-user-btn"]').click()
    cy.get('[data-cy="add-Evaluadores-btn"]').click()
    cy.get('[data-cy="search-user-input"]').type('Victoria Martin')
    cy.get('[data-cy="Victoria-result"]').click()
    cy.get('[data-cy="add-user-btn"]').click()
    cy.get('[data-cy="add-Evaluadores-btn"]').click()
    cy.get('[data-cy="search-user-input"]').type('Joseph Rodriguez')
    cy.get('[data-cy="Joseph-result"]').click()
    cy.get('[data-cy="add-user-btn"]').click()
    cy.get('[data-cy="create-anteproyecto-btn"]').click()
  })
})