describe('template spec', () => {
  it('passes', () => {
    cy.visit('/login')
    cy.get('[data-cy="email-input"]').type('admin@admin.com')
    cy.get('[data-cy="password-input"]').type('123123')
    cy.get('[data-cy="login-button"]').click()
    cy.get('[data-ct="anteproyectos-card"]').click()
    cy.get('[data-cy="create-btn"]').click()
    cy.get('[data-cy="radicado-input"]').type('123456')
    cy.get('[data-cy="titulo-input"]').type('Anteproyecto de prueba 1')
    cy.get('[data-cy="add-Autores-btn"]').click()
    cy.get('[data-cy="search-user-input"]').type('usuario')
    cy.get('[data-cy="Nombres usuario-result"]').click()
    cy.get('[data-cy="add-user-btn"]').click()
    cy.get('[data-cy="add-Directores-btn"]').click()
    cy.get('[data-cy="search-user-input"]').type('director')
    cy.get('[data-cy="Nombres director 1-result"]').click()
    cy.get('[data-cy="add-user-btn"]').click()
    cy.get('[data-cy="add-Evaluadores-btn"]').click()
    cy.get('[data-cy="search-user-input"]').type('evaluador')
    cy.get('[data-cy="Nombres evaluador 1-result"]').click()
    cy.get('[data-cy="add-user-btn"]').click()
    cy.get('[data-cy="add-Evaluadores-btn"]').click()
    cy.get('[data-cy="search-user-input"]').type('evaluador')
    cy.get('[data-cy="Nombres evaluador 2-result"]').click()
    cy.get('[data-cy="add-user-btn"]').click()
    cy.get('[data-cy="create-anteproyecto-btn"]').click()
  })
})